
CREATE TABLE IF NOT EXISTS WALLETS (
    ID SERIAL PRIMARY KEY, 
    FULL_NAME VARCHAR(100), 
    CPF BIGINT, EMAIL VARCHAR(100), 
    "PASSWORD" VARCHAR(100), 
    "TYPE" INT, 
    BALANCE DECIMAL(10, 2), 
    "VERSION" BIGINT
);


CREATE TABLE IF NOT EXISTS TRANSACTIONS (
    ID SERIAL PRIMARY KEY, 
    PAYER INT, 
    PAYEE INT, 
    "VALUE" DECIMAL(10, 2), 
    CREATED_AT TIMESTAMP, 
    FOREIGN KEY (PAYER) REFERENCES WALLETS (ID),
    FOREIGN KEY (PAYEE) REFERENCES WALLETS (ID)
);

CREATE UNIQUE INDEX idx_unique_cpf ON tbl_wallets(CPF);
CREATE UNIQUE INDEX idx_unique_email ON tbl_wallets(EMAIL);